version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test

builds:
  - id: up
    binary: up
    ldflags:
      - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
    goarm:
      - "7"
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le

  - id: up-win
    binary: up
    ldflags:
      - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      post:
        - upx -9 "{{ .Path }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE.txt
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - package_name: up
    maintainer: jesusprubio <jesusprubio@gmail.com>
    homepage: https://github.com/jesusprubio/up
    description: |
      Troubleshoot problems with your Internet connection based on different protocols and well-known public servers.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    dependencies:
      - git

winget:
  - name: up
    publisher: jesusprubio
    license: MIT
    short_description: Internet connection troubleshooting tool
    description: |
      Troubleshoot problems with your Internet connection based on different protocols and well-known public servers.
    homepage: https://github.com/jesusprubio/up
    tags:
      - networking
      - troubleshooting
      - utility
    repository:
      owner: jesusprubio
      name: winget-pkgs
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: main

brews:
  - repository:
      owner: jesusprubio
      name: homebrew-tap
    commit_author:
      name: jesusprubio
      email: jesusprubio@gmail.com
    homepage: https://github.com/jesusprubio/up
    description: |
      Troubleshoot problems with your Internet connection based on different protocols and well-known public servers.
    license: MIT
    test: |
      system "#{bin}/up --version"
    dependencies:
      - git

